In [1]:
import pandas as pd

In [2]:
D = pd.read_csv("https://github.com/junaart/ForStudents/raw/refs/heads/main/R/Zachet/DataSets/10.csv",sep=";")
display(D)

,okato,Субсидии на ГЗ из местных бюджетов,Субсидии на ГЗ из федерального бюджета,Субсидии на НИОКР из местного бюджета,Субсидии на НИОКР из федерального бюджета,Гранты из местного бюджета,Гранты из федерального бюджета,Гранты из прочих источников,Конкурсное финансирование из местного бюджета,Конкурсное финансирование из федерального бюджета,Конкурсное финансирование из прочих источников
0,1000000000,"4853,7","151428,9",0,"111490,7",4771,"38493,3",0,"3848,8","135930,7",7494
1,3000000000,4986,473810,"1986,2","83328,5",69321,18770,0,"10339,3",2399,"45896,8"
2,4000000000,0,"789836,7","4483,9","367127,5","26258,8","208412,7",0,"6116,6",135887,"81352,6"
3,5000000000,20,"2609402,1","23246,1","202671,1","16971,6","120107,1",0,"260,8","25615,4","434937,3"
4,7000000000,"16107,2","164127,2","1803,5","23146,1",200,"17333,9",0,900,1200,"11334,8"
...,...,...,...,...,...,...,...,...,...,...,...
77,94000000000,"17637,2","154377,8",0,"14343,5",0,"705,1",0,"1561,4",1158,"23897,1"
78,95000000000,26919,"2584,1",0,1200,"1613,9","7274,9",0,"1791,3",0,0
79,96000000000,0,"1994,2",0,0,445,1878,0,0,0,0
80,97000000000,0,"4670,7",0,"31575,9","318,9","18221,5",0,0,"201861,7","3179,4"
81,98000000000,218723,"1245978,4","59454,5","86745,9",0,"48324,4",0,"20364,9",0,"5648,3"

In [3]:
import redis as rd

In [9]:
r = rd.Redis()
key = "my_key."
for i in range(len(D["okato"])):
    r.set(key+str(i),str(D["okato"].iloc[i]))

In [10]:
D.columns

Index(['okato', 'Субсидии на ГЗ из местных бюджетов',
       'Субсидии на ГЗ из федерального бюджета',
       'Субсидии на НИОКР из местного бюджета',
       'Субсидии на НИОКР из федерального бюджета',
       'Гранты из местного бюджета', 'Гранты из федерального бюджета',
       'Гранты из прочих источников',
       'Конкурсное финансирование из местного бюджета',
       'Конкурсное финансирование из федерального бюджета',
       'Конкурсное финансирование из прочих источников'],
      dtype='object')

In [11]:
r = rd.Redis()
key = "my_key2."
for i in range(len(D["Субсидии на ГЗ из местных бюджетов"])):
    r.set(key+str(i),str(D["Субсидии на ГЗ из местных бюджетов"].iloc[i]))

In [12]:
r = rd.Redis()
key = "my_key3."
for i in range(len(D["Субсидии на ГЗ из федерального бюджета"])):
    r.set(key+str(i),str(D["Субсидии на ГЗ из федерального бюджета"].iloc[i]))

In [13]:
r = rd.Redis()
key = "my_key4."
for i in range(len(D["Субсидии на НИОКР из местного бюджета"])):
    r.set(key+str(i),str(D["Субсидии на НИОКР из местного бюджета"].iloc[i]))

In [14]:
r = rd.Redis()
key = "my_key5."
for i in range(len(D["Субсидии на НИОКР из федерального бюджета"])):
    r.set(key+str(i),str(D["Субсидии на НИОКР из федерального бюджета"].iloc[i]))

In [17]:
r = rd.Redis()
key = "my_key6."
for i in range(len(D["Гранты из местного бюджета"])):
    r.set(key+str(i),str(D["Гранты из местного бюджета"].iloc[i]))

In [ ]:
r = rd.Redis()
key = "my_key7."
for i in range(len(D["Гранты из федерального бюджета"])):
    r.set(key+str(i),str(D["Гранты из федерального бюджета"].iloc[i]))

In [18]:
r = rd.Redis()
key = "my_key8."
for i in range(len(D["Гранты из прочих источников"])):
    r.set(key+str(i),str(D["Гранты из прочих источников"].iloc[i]))

In [19]:
r = rd.Redis()
key = "my_key9."
for i in range(len(D["Конкурсное финансирование из местного бюджета"])):
    r.set(key+str(i),str(D["Конкурсное финансирование из местного бюджета"].iloc[i]))

In [20]:
r = rd.Redis()
key = "my_key10."
for i in range(len(D["Конкурсное финансирование из федерального бюджета"])):
    r.set(key+str(i),str(D["Конкурсное финансирование из федерального бюджета"].iloc[i]))

In [21]:
r = rd.Redis()
key = "my_key11."
for i in range(len(D["Конкурсное финансирование из прочих источников"])):
    r.set(key+str(i),str(D["Конкурсное финансирование из прочих источников"].iloc[i]))